#!/usr/bin/env php
<?php
// application.php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('COMPOSER_INSTALL', $file);
        break;
    }
}

if (!defined('COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require COMPOSER_INSTALL;

use Symfony\Component\Console\Application;
use Petrica\StatsdSystem\Command\NotifyCommand;

$application = new Application();
$application->add(new NotifyCommand());
$application->run();